# YML是一种文件格式，全称为YAML（YAML Ain't Markup Language），SpringBoot通常使用YML作为项目配置。
# 它是一种人类可读的、简洁明了的数据序列化格式。YAML文件格式通常用于配置文件、数据交换、消息传递和其他应用程序。
# 可以通过文本编辑器进行编辑，也可以通过程序进行解析。YML文件格式是一种以层级缩进的方式表示程序数据结构的格式。
# 在数据表示方面比XML等格式更加简洁清晰易读。YML文件格式通常以“.yml”为扩展名。

# 服务端口
server:
  port: 9271

# Spring配置
spring:
  application:
    name: parking
  # 数据库配置
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/DB_Parking?useUnicode=true&characterEncoding=utf-8
          username: root
          password: cheng42338cz
          druid:
            initialSize: 5
            minIdle: 10
            maxActive: 20
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            maxEvictableIdleTimeMillis: 900000
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
  #上传文件大小
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 800MB

#mybatis plus
mybatis-plus:
  # mapper扫描包
  mapper-package: com.shanzhu.**.mapper
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.rabbiter.**.domain
  configuration:
    map-underscore-to-camel-case: true

#sa-token设置
sa-token:
  token-name: satoken
  timeout: 1800
  activity-timeout: 1800
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false

#日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug
